#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <algorithm>
using namespace std;
int mainMenu();
int mainMenu2();
void showStudentMenu();
void showBooklist();
void showlibadminmenu();
void showadminmenu();
void showstudentadmin();
void showteacheradmin();
void showlibadmin();
void showbookadmin();
//void borrowBook();
//void returnBook();
//int updateBookData();
//int addbook();
